export type AlbumPhoto = {
  filename: string  // e.g. 'PSG-26.jpg' — just the filename, not full path
  caption?: string
}

export type Album = {
  slug: string
  title: string
  tag: string       // eyebrow label (matches Photographs card tag)
  date: string
  location: string
  coverImage: string // full path from /public
  photos: AlbumPhoto[]
}

export const albums: Album[] = [
  {
    slug: 'fifa-intercontinental-cup',
    title: 'FIFA Intercontinental Cup',
    tag: 'FIFA Intercontinental Cup',
    date: 'December 2024',
    location: 'Qatar',
    coverImage: '/PSG-88.jpg',
    photos: [
      { filename: '/PSG-88.jpg', caption: 'Paris Saint-Germain — Intercontinental Champions' },
      { filename: 'IMG_2793.jpg' },
      { filename: 'IMG_2828.jpg' },
      { filename: 'IMG_2848.jpg' },
      { filename: 'IMG_2863.jpg' },
      { filename: 'IMG_3091.jpg' },
      { filename: 'IMG_3092.jpg' },
      { filename: 'IMG_3136.jpg' },
      { filename: 'IMG_4817.jpg' },
      { filename: 'IMG_4871.jpg' },
      { filename: 'IMG_4907.jpg' },
      { filename: 'IMG_4923.jpg' },
      { filename: 'IMG_4970.jpg' },
      { filename: 'IMG_4977.jpg' },
      { filename: 'IMG_5006.jpg' },
      { filename: 'IMG_5021.jpg' },
      { filename: 'IMG_5036.jpg' },
      { filename: 'IMG_5046.jpg' },
      { filename: 'IMG_5047.jpg' },
      { filename: 'IMG_5065.jpg' },
      { filename: 'IMG_5080.jpg' },
      { filename: 'IMG_5104.jpg' },
      { filename: 'IMG_5151.jpg' },
      { filename: 'IMG_5161.jpg' },
      { filename: 'IMG_5194.jpg' },
      { filename: 'IMG_5217.jpg' },
      { filename: 'PSG-26.jpg' },
      { filename: 'PSG-27.jpg' },
      { filename: 'PSG-28.jpg' },
      { filename: 'PSG-29.jpg' },
      { filename: 'PSG-30.jpg' },
      { filename: 'PSG-30-2.jpg' },
      { filename: 'PSG-30-3.jpg' },
      { filename: 'PSG-31.jpg' },
      { filename: 'PSG-32.jpg' },
      { filename: 'PSG-33.jpg' },
      { filename: 'PSG-34.jpg' },
      { filename: 'PSG-35.jpg' },
      { filename: 'PSG-36.jpg' },
      { filename: 'PSG-37.jpg' },
      { filename: 'PSG-38.jpg' },
      { filename: 'PSG-39.jpg' },
      { filename: 'PSG-40.jpg' },
      { filename: 'PSG-41.jpg' },
      { filename: 'PSG-42.jpg' },
      { filename: 'PSG-43.jpg' },
      { filename: 'PSG-44.jpg' },
      { filename: 'PSG-45.jpg' },
      { filename: 'PSG-46.jpg' },
      { filename: 'PSG-47.jpg' },
      { filename: 'PSG.S-7.jpg' },
      { filename: 'PSG.S-8.jpg' },
      { filename: 'PSG.S-9.jpg' },
      { filename: 'PSG.S-10.jpg' },
      { filename: 'PSG.S-11.jpg' },
      { filename: 'PSG.S-12.jpg' },
      { filename: 'PSG.S-13.jpg' },
      { filename: 'PSG.S-14.jpg' },
      { filename: 'PSG.S-15.jpg' },
      { filename: 'PSG.S-16.jpg' },
      { filename: 'PSG.S-17.jpg' },
      { filename: 'PSG.S-18.jpg' },
      { filename: 'PSG.S-19.jpg' },
      { filename: 'PSG.S-20.jpg' },
      { filename: 'PSG.S-21.jpg' },
      { filename: 'PSG.S-22.jpg' },
      { filename: 'PSG.S-23.jpg' },
      { filename: 'PSG.S-24.jpg' },
      { filename: 'PSG.S-25.jpg' },
      { filename: 'PSG.S-26.jpg' },
      { filename: 'PSG.S-27.jpg' },
      { filename: 'PSG.S-28.jpg' },
      { filename: 'PSG.S-29.jpg' },
      { filename: 'PSG.S-30.jpg' },
      { filename: 'PSG.S-31.jpg' },
      { filename: 'PSG.S-32.jpg' },
      { filename: 'PSG.S-33.jpg' },
      { filename: 'PSG.S-34.jpg' },
      { filename: 'PSG.S-35.jpg' },
      { filename: 'PSG.S-36.jpg' },
      { filename: 'PSG.S-37.jpg' },
      { filename: 'PSG.S-38.jpg' },
      { filename: 'PSG.S-39.jpg' },
      { filename: 'PSG.S-40.jpg' },
      { filename: 'PSG.S-41.jpg' },
      { filename: 'PSG.S-42.jpg' },
      { filename: 'PSG.S-43.jpg' },
      { filename: 'PSG.S-44.jpg' },
      { filename: 'PSG.S-45.jpg' },
      { filename: 'PSG.S-46.jpg' },
      { filename: 'PSG.S-47.jpg' },
      { filename: 'PSG.S-48.jpg' },
      { filename: 'PSG.S-49.jpg' },
      { filename: 'PSG.S-50.jpg' },
      { filename: 'PSG.S-51.jpg' },
      { filename: 'PSG.S-52.jpg' },
      { filename: 'PSG.S-53.jpg' },
      { filename: 'PSG.S-54.jpg' },
      { filename: 'PSG.S-55.jpg' },
      { filename: 'PSG.S-56.jpg' },
      { filename: 'PSG.S-57.jpg' },
      { filename: 'PSG.S-58.jpg' },
      { filename: 'PSG.S-59.jpg' },
      { filename: 'PSG.S-60.jpg' },
      { filename: 'PSG.S-61.jpg' },
      { filename: 'PSG.S-62.jpg' },
      { filename: 'PSG.S-63.jpg' },
      { filename: 'PSG.S-64.jpg' },
      { filename: 'PSG.S-65.jpg' },
      { filename: 'PSG.S-66.jpg' },
    ],
  },
  {
    slug: 'african-athletics-championship',
    title: 'African Athletics Championship',
    tag: 'African Athletics Championship',
    date: '2024',
    location: 'Accra, Ghana',
    coverImage: '/IMG_0949A90B.jpg',
    photos: [
      { filename: '/IMG_0949A90B.jpg', caption: 'African Athletics Championship — Accra 2024' },
      { filename: 'IMG_0055A90B.jpg' },
      { filename: 'IMG_0061A90B.jpg' },
      { filename: 'IMG_0064A90B.jpg' },
      { filename: 'IMG_0079A90B.jpg' },
      { filename: 'IMG_0086A90B.jpg' },
      { filename: 'IMG_0088A90B.jpg' },
      { filename: 'IMG_0089A90B.jpg' },
      { filename: 'IMG_0089A90B-2.jpg' },
      { filename: 'IMG_0098A90B.jpg' },
      { filename: 'IMG_0140A90B.jpg' },
      { filename: 'IMG_0147A90B.jpg' },
      { filename: 'IMG_0158A90B.jpg' },
      { filename: 'IMG_0158A90B copy.jpg' },
      { filename: 'IMG_0174A90B.jpg' },
      { filename: 'IMG_0176A90B.jpg' },
      { filename: 'IMG_0176A90B copy.jpg' },
      { filename: 'IMG_0185A90B.jpg' },
      { filename: 'IMG_0186A90B.jpg' },
      { filename: 'IMG_0186A90B copy.jpg' },
      { filename: 'IMG_0189A90B.jpg' },
      { filename: 'IMG_0189A90B copy.jpg' },
      { filename: 'IMG_0199A90B.jpg' },
      { filename: 'IMG_0211A90B.jpg' },
      { filename: 'IMG_0211A90B-2.jpg' },
      { filename: 'IMG_0211A90B-3.jpg' },
      { filename: 'IMG_0218A90B.jpg' },
      { filename: 'IMG_0230A90B.jpg' },
      { filename: 'IMG_0246A90B.jpg' },
      { filename: 'IMG_0251A90B.jpg' },
      { filename: 'IMG_0255A90B.jpg' },
      { filename: 'IMG_0258A90B.jpg' },
      { filename: 'IMG_0259A90B.jpg' },
      { filename: 'IMG_0261A90B.jpg' },
      { filename: 'IMG_0263A90B.jpg' },
      { filename: 'IMG_0265A90B.jpg' },
      { filename: 'IMG_0267A90B.jpg' },
      { filename: 'IMG_0272A90B.jpg' },
      { filename: 'IMG_0276A90B.jpg' },
      { filename: 'IMG_0277A90B.jpg' },
      { filename: 'IMG_0278A90B.jpg' },
      { filename: 'IMG_0279A90B.jpg' },
      { filename: 'IMG_0283A90B.jpg' },
      { filename: 'IMG_0284A90B.jpg' },
      { filename: 'IMG_0303A90B.jpg' },
      { filename: 'IMG_0306A90B.jpg' },
      { filename: 'IMG_0307A90B.jpg' },
      { filename: 'IMG_0308A90B.jpg' },
      { filename: 'IMG_0309A90B.jpg' },
      { filename: 'IMG_0310A90B.jpg' },
      { filename: 'IMG_0313A90B.jpg' },
      { filename: 'IMG_0314A90B.jpg' },
      { filename: 'IMG_0315A90B.jpg' },
      { filename: 'IMG_0318A90B.jpg' },
      { filename: 'IMG_0321A90B.jpg' },
      { filename: 'IMG_0324A90B.jpg' },
      { filename: 'IMG_0324A90B-2.jpg' },
      { filename: 'IMG_0325A90B.jpg' },
      { filename: 'IMG_0330A90B.jpg' },
      { filename: 'IMG_0337A90B.jpg' },
      { filename: 'IMG_0338A90B.jpg' },
      { filename: 'IMG_0342A90B.jpg' },
      { filename: 'IMG_0349A90B.jpg' },
      { filename: 'IMG_0355A90B.jpg' },
      { filename: 'IMG_0362A90B.jpg' },
      { filename: 'IMG_0363A90B.jpg' },
      { filename: 'IMG_0371A90B.jpg' },
      { filename: 'IMG_0373A90B.jpg' },
      { filename: 'IMG_0374A90B.jpg' },
      { filename: 'IMG_0383A90B.jpg' },
      { filename: 'IMG_0390A90B.jpg' },
      { filename: 'IMG_0396A90B.jpg' },
      { filename: 'IMG_0400A90B.jpg' },
      { filename: 'IMG_0402A90B.jpg' },
      { filename: 'IMG_0410A90B.jpg' },
      { filename: 'IMG_0414A90B.jpg' },
      { filename: 'IMG_0417A90B.jpg' },
      { filename: 'IMG_0418A90B.jpg' },
      { filename: 'IMG_0432A90B.jpg' },
      { filename: 'IMG_0444A90B.jpg' },
      { filename: 'IMG_0453A90B.jpg' },
      { filename: 'IMG_0457A90B.jpg' },
      { filename: 'IMG_0461A90B.jpg' },
      { filename: 'IMG_0463A90B.jpg' },
      { filename: 'IMG_0472A90B.jpg' },
      { filename: 'IMG_0476A90B.jpg' },
      { filename: 'IMG_0477A90B.jpg' },
      { filename: 'IMG_0478A90B.jpg' },
      { filename: 'IMG_0492A90B.jpg' },
      { filename: 'IMG_0497A90B.jpg' },
      { filename: 'IMG_0513A90B.jpg' },
      { filename: 'IMG_0556A90B.jpg' },
      { filename: 'IMG_0558A90B.jpg' },
      { filename: 'IMG_0560A90B.jpg' },
      { filename: 'IMG_0576A90B.jpg' },
      { filename: 'IMG_0651A90B.jpg' },
      { filename: 'IMG_0652A90B.jpg' },
      { filename: 'IMG_0654A90B.jpg' },
      { filename: 'IMG_0663A90B.jpg' },
      { filename: 'IMG_0667A90B.jpg' },
      { filename: 'IMG_0676A90B.jpg' },
      { filename: 'IMG_0677A90B.jpg' },
      { filename: 'IMG_0684A90B.jpg' },
      { filename: 'IMG_0686A90B.jpg' },
      { filename: 'IMG_0688A90B.jpg' },
      { filename: 'IMG_0691A90B.jpg' },
      { filename: 'IMG_0692A90B.jpg' },
      { filename: 'IMG_0695A90B.jpg' },
      { filename: 'IMG_0701A90B.jpg' },
      { filename: 'IMG_0704A90B.jpg' },
      { filename: 'IMG_0705A90B.jpg' },
      { filename: 'IMG_0709A90B.jpg' },
      { filename: 'IMG_0711A90B.jpg' },
      { filename: 'IMG_0713A90B.jpg' },
      { filename: 'IMG_0715A90B.jpg' },
      { filename: 'IMG_0719A90B.jpg' },
      { filename: 'IMG_0721A90B.jpg' },
      { filename: 'IMG_0722A90B.jpg' },
      { filename: 'IMG_0723A90B.jpg' },
      { filename: 'IMG_0729A90B.jpg' },
      { filename: 'IMG_0730A90B.jpg' },
      { filename: 'IMG_0731A90B.jpg' },
      { filename: 'IMG_0733A90B.jpg' },
      { filename: 'IMG_0740A90B.jpg' },
      { filename: 'IMG_0743A90B.jpg' },
      { filename: 'IMG_0744A90B.jpg' },
      { filename: 'IMG_0765A90B.jpg' },
      { filename: 'IMG_0773A90B.jpg' },
      { filename: 'IMG_0779A90B.jpg' },
      { filename: 'IMG_0780A90B.jpg' },
      { filename: 'IMG_0781A90B.jpg' },
      { filename: 'IMG_0782A90B.jpg' },
      { filename: 'IMG_0783A90B.jpg' },
      { filename: 'IMG_0784A90B.jpg' },
      { filename: 'IMG_0785A90B.jpg' },
      { filename: 'IMG_0786A90B.jpg' },
      { filename: 'IMG_0789A90B.jpg' },
      { filename: 'IMG_0791A90B.jpg' },
      { filename: 'IMG_0792A90B.jpg' },
      { filename: 'IMG_0793A90B.jpg' },
      { filename: 'IMG_0803A90B.jpg' },
      { filename: 'IMG_0818A90B.jpg' },
      { filename: 'IMG_0840A90B.jpg' },
      { filename: 'IMG_0850A90B.jpg' },
      { filename: 'IMG_0855A90B.jpg' },
      { filename: 'IMG_0880A90B.jpg' },
      { filename: 'IMG_0883A90B.jpg' },
      { filename: 'IMG_0884A90B.jpg' },
      { filename: 'IMG_0897A90B.jpg' },
      { filename: 'IMG_0942A90B.jpg' },
      { filename: 'IMG_0943A90B.jpg' },
      { filename: 'IMG_0944A90B.jpg' },
      { filename: 'IMG_0945A90B.jpg' },
      { filename: 'IMG_0946A90B.jpg' },
      { filename: 'IMG_0963A90B.jpg' },
      { filename: 'IMG_0974A90B.jpg' },
    ],
  },
  {
    slug: 'fifa-arab-cup',
    title: 'FIFA Arab Cup',
    tag: 'FIFA Arab Cup',
    date: '2024',
    location: 'UAE',
    coverImage: '/UAEMOROC-13.jpg',
    photos: [
      { filename: 'DSC06921.jpg' },
      { filename: 'DSC06923.jpg' },
      { filename: 'DSC06927.jpg' },
      { filename: 'DSC06928.jpg' },
      { filename: 'DSC06930.jpg' },
      { filename: 'DSC06936.jpg' },
      { filename: 'DSC06955.jpg' },
      { filename: 'DSC06957.jpg' },
      { filename: 'DSC06967.jpg' },
      { filename: 'DSC06969.jpg' },
      { filename: 'DSC06997.jpg' },
      { filename: 'DSC_0794.jpg' },
      { filename: 'DSC_0817.jpg' },
      { filename: 'DSC_0819.jpg' },
      { filename: 'DSC_0830.jpg' },
      { filename: 'DSC_0836.jpg' },
      { filename: 'DSC_0839.jpg' },
      { filename: 'DSC_0847.jpg' },
      { filename: 'DSC_0852.jpg' },
      { filename: 'DSC_0861.jpg' },
      { filename: 'DSC_0864.jpg' },
      { filename: 'DSC_0869.jpg' },
      { filename: 'DSC_0870.jpg' },
      { filename: 'DSC_0874.jpg' },
      { filename: 'DSC_0877.jpg' },
      { filename: 'DSC_0879.jpg' },
      { filename: 'DSC_0881.jpg' },
      { filename: 'DSC_0882.jpg' },
      { filename: 'DSC_0883.jpg' },
      { filename: 'DSC_1087.jpg' },
      { filename: 'DSC_1094.jpg' },
      { filename: 'DSC_1096.jpg' },
      { filename: 'DSC_1099.jpg' },
      { filename: 'DSC_1100.jpg' },
      { filename: 'DSC_1102.jpg' },
      { filename: 'DSC_1106.jpg' },
      { filename: 'DSC_1107.jpg' },
      { filename: 'DSC_1114.jpg' },
      { filename: 'DSC_1123.jpg' },
      { filename: 'DSC_1132.jpg' },
      { filename: 'DSC_1140.jpg' },
      { filename: 'DSC_1152.jpg' },
      { filename: 'DSC_1153.jpg' },
      { filename: 'DSC_1156.jpg' },
      { filename: 'DSC_1161.jpg' },
      { filename: 'DSC_1179.jpg' },
      { filename: 'DSC_1181.jpg' },
      { filename: 'DSC_1189.jpg' },
      { filename: 'DSC_1195.jpg' },
      { filename: 'DSC_1197.jpg' },
      { filename: 'DSC_1198.jpg' },
      { filename: 'DSC_1201.jpg' },
      { filename: 'DSC_1202.jpg' },
      { filename: 'IMG_1655.jpg' },
      { filename: 'IMG_1662.jpg' },
      { filename: 'IMG_1667.jpg' },
      { filename: 'IMG_1669.jpg' },
      { filename: 'IMG_1678.jpg' },
      { filename: 'IMG_1681.jpg' },
      { filename: 'IMG_1687.jpg' },
      { filename: 'IMG_1689.jpg' },
      { filename: 'IMG_1696.jpg' },
      { filename: 'IMG_1697.jpg' },
      { filename: 'IMG_1711.jpg' },
      { filename: 'IMG_1714.jpg' },
      { filename: 'IMG_1926.jpg' },
      { filename: 'IMG_1930.jpg' },
      { filename: 'IMG_1932.jpg' },
      { filename: 'IMG_1947.jpg' },
      { filename: 'IMG_1992.jpg' },
      { filename: 'IMG_2063.jpg' },
      { filename: 'IMG_2065.jpg' },
      { filename: 'IMG_2070.jpg' },
      { filename: 'IMG_2073.jpg' },
      { filename: 'IMG_2074.jpg' },
      { filename: 'IMG_2079.jpg' },
      { filename: 'IMG_2095.jpg' },
      { filename: 'IMG_2102.jpg' },
      { filename: 'IMG_2128.jpg' },
      { filename: 'IMG_2134.jpg' },
      { filename: 'IMG_2137.jpg' },
      { filename: 'IMG_2139.jpg' },
      { filename: 'IMG_2147.jpg' },
      { filename: 'UAEMOROC-7.jpg' },
      { filename: 'UAEMOROC-8.jpg' },
      { filename: 'UAEMOROC-9.jpg' },
      { filename: 'UAEMOROC-10.jpg' },
      { filename: 'UAEMOROC-11.jpg' },
      { filename: 'UAEMOROC-12.jpg' },
      { filename: 'UAEMOROC-13.jpg', caption: 'From Casablanca to Arab Kings' },
      { filename: 'UAEMOROC-14.jpg' },
      { filename: 'UAEMOROC-15.jpg' },
      { filename: 'UAEMOROC-16.jpg' },
      { filename: 'UAEMOROC-17.jpg' },
      { filename: 'UAEMOROC-18.jpg' },
      { filename: 'UAEMOROC-25.jpg' },
      { filename: 'UAEMOROC-31.jpg' },
      { filename: 'UAEMOROC-32.jpg' },
      { filename: 'UAEMOROC-33.jpg' },
      { filename: 'UAEMOROC-34.jpg' },
      { filename: 'UAEMOROC-35.jpg' },
      { filename: 'UAEMOROC-36.jpg' },
      { filename: 'UAEMOROC-37.jpg' },
      { filename: 'UAEMOROC-38.jpg' },
      { filename: 'UAEMOROC-39.jpg' },
      { filename: 'UAEMOROC-40.jpg' },
      { filename: 'UAEMOROC-41.jpg' },
      { filename: 'UAEMOROC-42.jpg' },
      { filename: 'UAEMOROC-43.jpg' },
      { filename: 'UAEMOROC-44.jpg' },
      { filename: 'UAEMOROC-45.jpg' },
      { filename: 'UAEMOROC-46.jpg' },
      { filename: 'UAEMOROC-47.jpg' },
      { filename: 'UAEMOROC-48.jpg' },
      { filename: 'UAEMOROC-49.jpg' },
      { filename: 'UAEMOROC-50.jpg' },
      { filename: 'UAEMOROC-51.jpg' },
      { filename: 'UAEMOROC-52.jpg' },
      { filename: 'UAEMOROC-53.jpg' },
      { filename: 'UAEMOROC-54.jpg' },
      { filename: 'UAEMOROC-55.jpg' },
      { filename: 'UAEMOROC-56.jpg' },
      { filename: 'UAEMOROC-57.jpg' },
      { filename: 'UAEMOROC-58.jpg' },
      { filename: 'UAEMOROC-59.jpg' },
      { filename: 'UAEMOROC-60.jpg' },
      { filename: 'UAEMOROC-61.jpg' },
      { filename: 'UAEMOROC-62.jpg' },
      { filename: 'UAEMOROC-63.jpg' },
      { filename: 'UAEMOROC-64.jpg' },
      { filename: 'UAEMOROC-65.jpg' },
      { filename: 'UAEMOROC-66.jpg' },
    ],
  },
]

/** Returns the full image path for a given album photo */
export function photoPath(album: Album, photo: AlbumPhoto): string {
  // If the filename has no directory prefix it lives in the album subfolder.
  // If it starts with '/' it's already a root-relative path (covers shoot-level assets).
  if (photo.filename.startsWith('/')) return photo.filename
  return `/images/albums/${album.slug}/${photo.filename}`
}

export function getAlbum(slug: string): Album | undefined {
  return albums.find((a) => a.slug === slug)
}
